clang-tidy: Disable some new checks
Current code breaks with these and they don't seem to be helpful.

These were the warnings:

src/libbluechi/common/protocol.h:107:9: error: inital values in enum 'JobState' are not consistent, consider explicit initialization of all, none or only the first enumerator [readability-enum-initial-value,-warnings-as-errors]
  107 | typedef enum JobState {
      |         ^
  108 |         JOB_WAITING,
      |                     = 0
  109 |         JOB_RUNNING,
      |                     = 1
src/libbluechi/common/protocol.h:116:9: error: inital values in enum 'UnitActiveState' are not consistent, consider explicit initialization of all, none or only the first enumerator [readability-enum-initial-value,-warnings-as-errors]
  116 | typedef enum UnitActiveState {
      |         ^
  117 |         UNIT_ACTIVE,
      |                     = 0
  118 |         UNIT_RELOADING,
      |                        = 1
  119 |         UNIT_INACTIVE,
      |                       = 2
  120 |         UNIT_FAILED,
      |                     = 3
  121 |         UNIT_ACTIVATING,
      |                         = 4
  122 |         UNIT_DEACTIVATING,
      |                           = 5
  123 |         UNIT_MAINTENANCE,
      |                          = 6
  124 |         _UNIT_ACTIVE_STATE_MAX,
      |                                = 7
src/libbluechi/bus/utils.c:329:26: error: '*' has higher precedence than '+'; add parentheses to explicitly specify the order of operations [readability-math-missing-parentheses,-warnings-as-errors]
  329 |         char *r = malloc(strlen(s) * 3 + 1);
      |                          ^~~~~~~~~~~~~
      |                          (            )